Controllers/ActorsController.cs
using MoviesManager.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MoviesManager.Controllers
{
    public class ActorsController : Controller
    {
        private DBEntities DB = new DBEntities();

        public ActionResult Index()
        {
            return View(DB.ActorsList());
        }

        public ActionResult ActorsList(List<ActorView> actors)
        {
            return PartialView(actors);
        }
        [AdminAcces]
        public ActionResult Create()
        {
            ViewBag.SelectedFilms = new List<ListItem>();
            ViewBag.Films = DB.FilmListItems();
            SelectList countries = new SelectList(DB.CountryListItems(),"Id","Text",0,new[] { -1 });
            ViewBag.Countries = countries;
            return View(new ActorView());
        }

        [HttpPost]
        public ActionResult Create(ActorView actorView, List<int> SelectedItems/*Liste des Id des films sélectionés*/)
        {
            if (ModelState.IsValid)
            {
                if (actorView.Name == null || actorView.Name.Trim() == "")
                {
                    ModelState.AddModelError("Name", "");
                    return View(actorView);
                }
                if (actorView.Sexe < 0 || actorView.Sexe > 2)
                {
                    ModelState.AddModelError("Sexe", "");
                }
                DB.AddActor(actorView, SelectedItems);
                return RedirectToAction("Index");
            }
            return View(actorView);
           
        }
        [UserAcces]
        public ActionResult Details(int id)
        {
            Actor actor = DB.Actors.Find(id);
            ViewBag.Films = actor.FilmsList();
            Models.Country pays = DB.Countries.Find(actor.CountryId);
            if (pays != null)
                ViewBag.Country = pays;
            else
            {
                ViewBag.Country = new Models.Country();
                ViewBag.Country.Name = "Inconnu";
            }
            ViewBag.Sexe = actor.Sexe;
            return View(actor.ToActorView());
        }
        [AdminAcces]
        public ActionResult Edit(int id)
        {
            Actor actor = DB.Actors.Find(id);
            ViewBag.SelectedFilms = actor.FilmListItems();
            ViewBag.Films = DB.FilmListItems();
            SelectList countries = new SelectList(DB.CountryListItems(), "Id", "Text", actor.CountryId, new[] { -1 });
            ViewBag.Countries = countries;
            ViewBag.Sexes = actor.Sexe;
            return View(actor.ToActorView());
        }

        [HttpPost]
        public ActionResult Edit(ActorView actorView, List<int> SelectedItems/*Liste des Id des films sélectionés*/)
        {
            DB.UpdateActor(actorView, SelectedItems);
            return RedirectToAction("Index");
        }
        [AdminAcces]
        public ActionResult Delete(int id)
        {
            return View(DB.Actors.Find(id).ToActorView());
        }

        [HttpPost]
        public ActionResult Delete(ActorView actorView)
        {
            DB.RemoveActor(actorView);
            return RedirectToAction("Index");
        }
    }
}

Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MoviesManager.Models;

namespace MoviesManager.Controllers
{
    public class AdminController : Controller
    {
        private DBEntities DB = new DBEntities();

        [AdminAcces]
        public ActionResult UsersList()
        {
            User[] allUsers = Extension.getAllUsers(DB);
            User currentUser = OnlineUsers.GetSessionUser();
            if (currentUser != null)
            {
                ViewBag.CurrentUserId = currentUser.Id;
                return View(allUsers);
            }
            return null;
        }
        [AdminAcces]
        public ActionResult DeleteUser(string userName)
        {
            User userToDelete = DB.FindByUserName(userName);
            userToDelete.ToUserView().RemoveAvatar();
            List<Rating> lstRating = DB.Ratings.Where(r => r.UserId == userToDelete.Id).ToList();
            DB.Ratings.RemoveRange(lstRating);
            DB.Users.Remove(userToDelete);
            DB.SaveChanges();
            return RedirectToAction("UsersList"); 
        }
    }
}

Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MoviesManager.Models;

namespace MoviesManager.Controllers
{
    public class UsersController : Controller
    {
        private DBEntities DB = new DBEntities();

        public ActionResult Subscribe()
        {
            return View(new UserView());
        }
        [HttpPost]
        public ActionResult Subscribe(UserView userView)
        {
            if (ModelState.IsValid)
            {
                if (DB.UserExists(userView.UserName))
                {
                    ModelState.AddModelError("UserName", "Ce nom d'usager existe deja");
                    return View(userView);
                }
                userView.Password = userView.NewPassword;
                DB.AddUser(userView);

                return RedirectToAction("Login");
            }
            return View(userView);
        }
        public ActionResult Login()
        {
            return View(new LoginView());
        }
        [HttpPost]
        public ActionResult Login(LoginView loginView)
        {
            //if (ModelState.IsValid)
            //{
                User userFound = DB.FindByUserName(loginView.UserName);
                if (userFound != null)
                {
                    if (userFound.Password != loginView.Password)
                    {
                        ModelState.AddModelError("Password", "Mot de passe incorrect");
                        return View(loginView);
                    }
                }
                else
                {
                    ModelState.AddModelError("UserName", "ce nom d'usager n'existe pas");
                    return View(loginView);
                }
                OnlineUsers.AddSessionUser(userFound);
            //}
            return RedirectToAction("Profil");
        }
        [UserAcces]
        public ActionResult Profil()
        {
            UserView userView = OnlineUsers.GetSessionUser().ToUserView();
            ViewBag.PasswordChangeToken = Guid.NewGuid().ToString();
            return View(userView);
        }
        [HttpPost]
        public ActionResult Profil(UserView userView)
        {
            if (ModelState.IsValid)
            {

                string PasswordChangeToken = (string)Request["PasswordChangeToken"];
                User user = DB.FindByUserName(OnlineUsers.Find(userView.Id).UserName);
                if (userView.NewPassword.Equals(PasswordChangeToken))
                {
                    userView.Password = user.Password;
                }
                else
                {
                    userView.Password = userView.NewPassword;
                }
                DB.UpdateUser(userView);
                userView.CopyToUser(OnlineUsers.GetSessionUser());
            }
            return RedirectToAction("Profil");
        }
        public ActionResult Logout()
        {
            User currentUser = OnlineUsers.GetSessionUser();
            if (currentUser != null)
            {
                OnlineUsers.RemoveSessionUser();
            }
            return RedirectToAction("Login");
        }
    }
}

Views/Shared/_Layout.cshtml
@{
    MoviesManager.Models.User user = MoviesManager.Models.OnlineUsers.GetSessionUser();
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Gestionnaire de films</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (user == null)
                    {
                        <li>@Html.ActionLink("S'inscrire", "Subscribe", "Users")</li>
                        <li>@Html.ActionLink("Se connecter", "Login", "Users")</li>
                    }
                    @if (user != null)
                    {
                        MoviesManager.Models.UserView onlineUser = MoviesManager.Models.Extension.ToUserView(user);
                        <li>@Html.ActionLink("Films", "Index", "Films")</li>
                        <li>@Html.ActionLink("Acteurs", "Index", "Actors")</li>
                        <li>@Helper.AvatarProfilLink(onlineUser)</li>
                        if (user.Admin)
                        {
                            <li>@Html.ActionLink("Liste d'usagers", "UsersList", "Admin")</li>
                        }
                        <li>@Html.ActionLink("Déconnexion", "Logout", "Users")</li>

                    }

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>